# version: '3.8'

services:
  escapadas-app:
    build: .
    container_name: escapadas_servidor
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      # 1. Volumen para el código de la app (Excluyendo node_modules para evitar conflictos)
      - app:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
      
      # 2. Volumen persistente para tus DATOS (JSON e Imágenes) fuera del ciclo de vida del contenedor
      - datas:/app/dist/backend/datas
    
    develop:
      watch:
        - action: sync
          path: ./app
          target: app/src
          ignore:
            - node_modules/

    restart: always

volumes:
  app:
    name: escapadas-app
  datas:
    name: escapadas-datas
  node_modules:
    name: escapadas-node_modules
  dist:
    name: escapadas-dist