# =========================
# Imagen base
# =========================
FROM node:20-alpine

# =========================
# Directorio de trabajo
# =========================
WORKDIR /app

# =========================
# Instalar Gulp CLI global
# =========================
RUN npm install -g gulp-cli

# =========================
# Copiar package.json
# =========================
COPY package*.json ./

# =========================
# Instalar dependencias
# =========================
RUN npm install

# =========================
# Copiar proyecto completo
# =========================
COPY . .

# =========================
# Ejecutar gulp por defecto
# =========================
CMD ["npx", "gulp"]
